language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install: pip3 install -U scm-source

before_script:
  - sudo /etc/init.d/postgresql stop

script: ./mvnw clean verify

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
