spring:
  application:
    name: compass
  resources:
    add-mappings: false
  mvc:
    favicon.enabled: false
    throw-exception-if-no-handler-found: true
    dispatch-trace-request: true
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}/postgres?currentSchema=compass
    username: postgres
    password: postgres
    tomcat:
      default-auto-commit: false
      test-on-borrow: false
      # TRANSACTION_READ_COMMITTED
      default-transaction-isolation: 2

      # https://stackoverflow.com/questions/23850585/how-to-start-spring-boot-app-without-depending-on-database
      initial-size: 0
      min-idle: 0
  flyway:
    schemas:
      - compass
  jooq:
    sql-dialect: postgres

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/*+json
  use-forward-headers: true

twintip:
  mapping: /api
  yaml: "classpath:api/api.yaml"

management:
  server:
    add-application-context-header: false
    port: 7979
  health.db.enabled: false
  endpoints:
    jmx.unique-names: true
    web:
      base-path: ''
      exposure.include: '*'
      path-mapping:
        jolokia: jmx

tracer:
  stacked: true
  traces:
    X-Flow-ID: flow-id

logbook:
  exclude:
    - /favicon.ico
    - /.well-known/schema-discovery
    - /api
