swagger: '2.0'
info:
  title: Config API
  description: Configuration operations
  version: "0.1.0"
  contact:
    name: Pennybags
    url: https://docs.pennybags.zalan.do
    email: team-pennybags@zalando.de
host: config-service.pennybags.zalan.do
basePath: /api
schemes:
  - https
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog # obviously fake
    scopes:
      uid: Unique identifier of the user accessing the service.
tags:
  - name: dimension
    description: Dimension resources
  - name: config
    description: Config resources
paths:
  /configurations:
    get:
      tags: [config]
      responses:
        200:
          description: Configurations
          schema:
            type: object
            additionalProperties:
              # keys = configuration keys
              $ref: '#/definitions/Node'
  /configurations/{key}:
    get:
      tags: [config]
      responses:
        200:
          description: Configuration
          schema:
            $ref: '#/definitions/Node'
definitions:
  Problem:
    properties:
      type:
        type: string
        example: https://docs.example.org/problems
      status:
        type: integer
        format: int32
        example: 422
      title:
        type: string
        # TODO example
      detail:
        type: string
        # TODO example
      instance:
        type: string
        # TODO example
    required:
      - type
  Dimension:
    type: string
    format: uri
    example: https://docs.example.org/region
  Node:
    properties:
      dimension:
        $ref: '#/definitions/Dimension'
      values:
        type: object
        additionalProperties:
          # keys = dimension values
          # TODO how to represent "null" keys? or default cases
          $ref: '#/definitions/Node'
        example:
          eu-west-1:
            dimension: https://docs.example.org/availability-zone
            values:
              eu-west-1a:
                value: "209.131.41.48"
              eu-west-1b:
                value: "217.146.191.18"
              eu-west-1c:
                value: "216.39.58.78"
            value: false
      value:
        example: true
    # well, at least either (dimension, values) or value needs to be present 

